name: Go

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Test and Build orchd
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Go version
        run: go version

      - name: Go test
        run: go test ./...

      - name: Build orchd
        run: go build ./cmd/orchd

      # Optional: upload orchd as an artifact
      - name: Upload orchd binary
        uses: actions/upload-artifact@v4
        with:
          name: orchd
          path: orchd
          if-no-files-found: ignore
